# Generated by Django 5.1.3 on 2024-12-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_interes_rango_final_interes_rango_inicial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='interes',
            options={'ordering': ['id', 'rango_inicial'], 'verbose_name': 'Interes', 'verbose_name_plural': 'Interes'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['id'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='prenda',
            options={'ordering': ['id'], 'verbose_name': 'Prenda', 'verbose_name_plural': 'Prendas'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['id'], 'verbose_name': 'Prestamo', 'verbose_name_plural': 'Prestamos'},
        ),
    ]
