# Generated by Django 5.1.3 on 2024-12-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_remove_prenda_capital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='codigo',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='numero_factura',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
